import "./globals.css";
import { Poppins } from "next/font/google";

import { getLanguage } from "@/lib/getLanguage";

import Navigation from "@/components/global/Navigation";
import Footer from "@/components/global/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font--poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "de" }];
}

export default async function RootLayout({ children, params }) {
  const language = await getLanguage(params.lang);
  return (
    <html lang={params.lang}>
      <body className={`app ${poppins.variable}`}>
        <Navigation language={language.navigation} />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
